### ISSUE TITLE
The weight is not transposed properly

### ISSUE THREAD

**Issue by BrianOn99** [tgyg-jegli/tf_texture_net#1]
As mentioned in README, `The TensorFlow implementation is not completely identical.`

That is because you call np.transpose() instead of np.transpose(2,3,1,0).  Look at the documentation of tensorflow and torch, then you will notice it.

**Comment by tgyg** [comment]
I changed the transposing and updated the picture and the tensorflow models.
See commit 2fcdcfabb8d8b2d135457f48bac77b6ed87c1444

Thank you!

**Comment by BrianOn99** [comment]
Also thank you make this repo which guide me converting torch model to tensorflow and coreml.  It save my life.  I am just contributing a little bit back.
