### ISSUE TITLE
output image transform 'rgb' to 'bgr'?

### ISSUE THREAD

**Issue by mjiansun** [tgyg-jegli/tf_texture_net#2]
why author transform 'rgb' to 'bgr' at the output part?

**Comment by tgyg** [comment]
Please excuse my late answer. Honestly i do not know anymore for sure.
It may have its origin from the original model, which we imported from DmitryUlyanov/texture_nets.
In his code, Ulyanov transformed from [RGB to BGR](https://github.com/DmitryUlyanov/texture_nets/blob/master/src/utils.lua#L168). I hope this helps you to find an answer.
