### ISSUE TITLE
Error while converting torch model using stylize_torch_weights.py

### ISSUE THREAD

**Issue by encodingwaddles** [tgyg-jegli/tf_texture_net#3]
I'm getting the following error when I'm trying to use stylize_torch_weights.py. I trained my model using https://github.com/DmitryUlyanov/texture_nets and then moved the model inside tf_texture_net/model and updated the name in stylize_torch_weights.py. 

> 
Traceback (most recent call last):
  File "stylize_torch_weights.py", line 225, in <module>
    main()
  File "stylize_torch_weights.py", line 23, in main
    stylized_image = network(content_image)
  File "stylize_torch_weights.py", line 52, in network
    weights = np.transpose(lua_model.modules[2].weight.asNumpyArray(),(2,3,1,0))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 575, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array

> 

Do you know how I can fix this issue? I was able to test this code using the pretrained model provided by https://github.com/DmitryUlyanov/texture_nets and like you mention in the README, this code works for that pretrained model. I'm confused as to why the model I trained using the exact same method encounters this error. Does this code only work if the style image I used to train with is exactly the same size as the one https://github.com/DmitryUlyanov/texture_nets uses? 

Thanks for your help!

**Comment by tgyg** [comment]
The model Ulyanov published is not exactly the same as the one described in the paper.

See [https://github.com/DmitryUlyanov/texture_nets#testing](https://github.com/DmitryUlyanov/texture_nets#testing):

> You can find a pretrained model here. It is _not_ the model from the paper.

I assume you can adapt our implementation to the new model. Import the model as described in [our Readme - Section Import](https://github.com/tgyg-jegli/tf_texture_net/blob/master/README.md#import) and analyze the structure of the weights.
